---
title: "STAT 243 Final Project: ars package"
subtitle: "Install from Github: nwadsworth/ars"
author: "Narae Wadsworth, Daije Sun, Lyu Zheng"
date: "12/11/2018"
output: pdf_document
fontsize: 12 pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The Approach
We wrote our function assuming that the user will provide a continuous, smooth function and starting values. Our approach was to make our code very modular. We created many small functions so that we could check each part for bugs. We decided to store the data in a matrix with columns for the $x$ values, $h(x)$, $h'(x)$, and $z$. We first made a function (initial) to initialize this data matrix. We also made functions to get $u_k(x)$ and $l_k(x)$. Subsequently, we got the sample $x^*$ using the inverse CDF method in our get_sample function. Our next function (test) performs the squeezing and rejection test on the $x^*$. This function returns a logical vector where the first element denotes whether or not $x^*$ was accepted while the second element denotes whether or not we need to update the data matrix. Our next function (update_step) updates the data matrix by adding a new row for the point to be added. It then sorts and returns the data matrix. Our last function (check_dist) checks the distribution for log concavity and also checks for the border cases occuring with the uniform distribution and the exponential distribution. All of these functions are combined and used in our ars function. Our ars function starts by checking that the user supplied valid input then initializes the data matrix. Then while the number of accepted $x^*$'s is less than the number of desired samples, the function iterates through the sampling and updating step as neccessary. The function prints out the sample as well as a statement of how many data points were added to the data matrix. 

# Testing
We performed tests for each of our functions to ensure they each work properly. We also created tests within the main function to test for valid user input, i.e. that the initial starting points make sense and that the distribution is log-concave. To test the overall functionality of our ars function we tested to ensure that the generated sample was indeed coming from the specified distribution using the Kolmogorov-Smirnov Test. We tested the gamma distribution, the exponential distribution, and normal distribution. Lastly, we tested to ensure the function would give an error for non log-concave functions including the t-distribution and Cauchy distribution.

# Contributions
All three group members contributed to the code, in particular: Narae created the functions for the initialization step, Lyu created the functions for the sampling step, and Daije created the functions for the updating step. Daije created the overall ars function using all of the aforementioned parts. Testing was created by Lyu and Daije while Narae was responsible for putting together the R package and writing the documentation.
